### ISSUE TITLE
What's the appropriate name for this c client library

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#1]
Hi @brendandburns 

Now the development for c client library can start, first of all, could you please give a name for the c client library ? 

I nominate some candidates:

- libkubernetes.so/libkubernetes.dll
- libk8s.so/libk8s.dll
- libkubernetes-client.so/libkubernetes-client.dll
- libk8sclient.so/libk8sclient.dll

**Comment by brendandburns** [comment]
I think I like libkubernetes.so/dll

--brendan

________________________________

**Comment by palnabarun** [comment]
+1 for linkubernetes.{so, dll}

**Comment by ityuhui** [comment]
Thank you @brendandburns @palnabarun for the comments. I will use libkubernetes as the name.
