### ISSUE TITLE
Request to tag current code and release 0.2.0 for kuberntes v1.22

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#115]
Hi @brendandburns 

I want to tag the current code
```shell
git tag -a v0.2.0 -m "version 0.2.0"
```

and release it for kuberntes v1.22

What do you think about it ?

**Comment by brendandburns** [comment]
Sounds great, let's do it!

and eventually let's make this a github action that is manually triggered, similar to https://github.com/kubernetes-client/java/blob/master/.github/workflows/release.yml

**Comment by ityuhui** [comment]
Release 0.2.0
https://github.com/kubernetes-client/c/releases/tag/v0.2.0

I will work for the github action later.
