### ISSUE TITLE
Request to release 0.3.0 for kuberntes v1.23

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#120]
Hi @brendandburns 

I plan to release 0.3.0 for kuberntes v1.23

The detail is:

1. Manually cut a branch `release-0.3` from `master`

2. On this branch `release-0.3`, tag and release `v0.3.0` via GitHub Action https://github.com/kubernetes-client/c/actions/workflows/release.yml

**Comment by brendandburns** [comment]
Sounds good!

**Comment by ityuhui** [comment]
v0.3.0 has released.

https://github.com/kubernetes-client/c/releases/tag/v0.3.0
