### ISSUE TITLE
Memory Leak in kubeyaml_load_kubeconfig() in kubernetes/config/kube_config_yaml.c

### ISSUE THREAD

**Issue by hariramshankar** [kubernetes-client/c#134]
Hi,

I found a memory leak when calling kubeyaml_load_kubeconfig()

kubeyaml_load_kubeconfig creates a yaml parser object before attempting to read the kubeconfig file.

If opening the kubeconfig file failed for some reason, the function returns(-1) without freeing up the memory allocated to parser.

snippet of the code in question where the leak occurs 
```
    /* Create the Parser object. */
    yaml_parser_initialize(&parser);

    /* Set a file input. */
    FILE *input = NULL;
    if (kubeconfig->fileName) {
        input = fopen(kubeconfig->fileName, "rb");
        if (!input) {
            fprintf(stderr, "%s: Cannot open the file %s.[%s]\n", fname, kubeconfig->fileName, strerror(errno));
            return -1; <<<<<
        }
    } else {
        fprintf(stderr, "%s: The kubeconf file name needs be set by kubeconfig->fileName .\n", fname);
        return -1; <<<<<
    }
````

**Comment by ityuhui** [comment]
Thank you for reporting this issue.

Will fix it later.

**Comment by joyantamishu** [comment]
Any update on this?

**Comment by ityuhui** [comment]
I'll find a cycle to fix it in a few days.
Fix PRs from anyone are also welcome.
