### ISSUE TITLE
Is there an api to get node status?

### ISSUE THREAD

**Issue by yess1987** [kubernetes-client/c#136]
We need to use the c library to get the node status, is there a solution?

**Comment by ityuhui** [comment]
Is this OK ?

https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/CoreV1API.md#CoreV1API_readNodeStatus

**Comment by yess1987** [comment]
let me try and wait for my good news

**Comment by ityuhui** [comment]
Can you describe in detail about "the role of etcd" ?

e.g.
Is the etcd a built-in component of Kubernetes (for API Server to save cluster information) or something you deploy it for your workload ?

And is this what you want ?
```kubectl exec etcd-kind-control-plane -n kube-system -- etcdctl role list```

**Comment by yess1987** [comment]
I need to know which node is the leader in k8s, so consider using the leader in etcd

**Comment by ityuhui** [comment]
Can you find a solution for your requirement via `kubectl`?

The C client library only communicates with the Kubernetes API server, which behaves like client-go/kubectl.

**Comment by brendandburns** [comment]
You shouldn't need to look at etcd, you can look at the labels on the node to determine where the api server is, specifically the `node-role.kubernetes.io/control-plane` should be present on any nodes that contain the Kubernetes control plane.
