### ISSUE TITLE
How to get the content of condition in v1_node_status_t structure, condition is a list_t *

### ISSUE THREAD

**Issue by wcamellia** [kubernetes-client/c#142]
How to get the content of condition in v1_node_status_t structure, condition is a list_t *

**Comment by ityuhui** [comment]
The structure of `v1_node_status_t` is:
https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_status.md

And the element of list_t of condition is:
https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_condition.md

An example of iterating over a list is:

https://github.com/kubernetes-client/c/blob/8afde9c48b76fdf91f2507b43821ca58ea8e95bb/examples/list_pod/main.c#L23-L28

And the interfaces of `list_t` can be found at https://github.com/kubernetes-client/c/blob/master/kubernetes/include/list.h

**Comment by wcamellia** [comment]
> The structure of `v1_node_status_t` is: https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_status.md
> 
> And the element of list_t of `condition` is: https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_condition.md
> 
> An example of iterating over a list is:
> 
> https://github.com/kubernetes-client/c/blob/8afde9c48b76fdf91f2507b43821ca58ea8e95bb/examples/list_pod/main.c#L23-L28
> 
> And the interfaces of `list_t` can be found at https://github.com/kubernetes-client/c/blob/master/kubernetes/include/list.h

**Comment by wcamellia** [comment]
> The structure of `v1_node_status_t` is: https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_status.md
> 
> And the element of list_t of `condition` is: https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/v1_node_condition.md
> 
> An example of iterating over a list is:
> 
> https://github.com/kubernetes-client/c/blob/8afde9c48b76fdf91f2507b43821ca58ea8e95bb/examples/list_pod/main.c#L23-L28
> 
> And the interfaces of `list_t` can be found at https://github.com/kubernetes-client/c/blob/master/kubernetes/include/list.h


！Thank you very much for your reply，I tried to get the content of the “condition“” according to the example of “c/examples/list_pod/main.c)” but got null，Do you have any good solution？Thank you very much again！

**Comment by ityuhui** [comment]
It's better to use `gdb` to debug line by line.
And can you append your code snippet of iterating over the list `condition` here ?

**Comment by wcamellia** [comment]
Thanks  ，my test  code is as follows，i tried many times without success，Please boss  help me to check and forgive my lack of ability, thank you very much !
----------------------------------------------------
[test_code.txt](https://github.com/kubernetes-client/c/files/9554543/test_code.txt)
    v1_node_t* node_info = NULL;
    node_info = CoreV1API_readNode(apiClient,"cluster-node1",NULL);
    printf("return code=%ld\n", apiClient->response_code);
    listEntry_t *listEntry = NULL;
    printf("kind = %s\n", node_info->kind);
    printf("api_version = %s\n", node_info->api_version);
    v1_node_status_t * node_istatus = node_info->status;

    list_ForEach(listEntry, node_info->status->conditions)
    {
        cJSON *root = cJSON_Parse(listEntry->data);
        cJSON *item = cJSON_GetObjectItem(root,"conditions");
        int arry_size = cJSON_GetArraySize(item);
        printf("\tarry_size : %s\n", arry_size);

        char *name = cJSON_GetStringValue(item);
        printf("\tThe node condition : %s\n", name);
    }

**Comment by ityuhui** [comment]
Refer the following code please

```c
    v1_node_condition_t *nc = NULL;
    list_ForEach(listEntry, node_info->status->conditions)
    {
        nc = listEntry->data;
        if (nc) {
            if (nc->status) {
                printf("Status: %s\n", nc->status);
            }
            if (nc->type) {
                printf("Type: %s\n", nc->type);
            }
            if (nc->message) {
                printf("Message: %s\n", nc->message);
            }
        }
    }
```

**Comment by wcamellia** [comment]
Thank you very much for your answer  and  excellence ！！！  I will try it for my test.
