### ISSUE TITLE
How to get node status (include "Ready" or "Notready")  like using "kubectl get nodes”  wiht “C api” ？

### ISSUE THREAD

**Issue by wcamellia** [kubernetes-client/c#143]

**Comment by wcamellia** [comment]
> You can check out the API list at https://github.com/kubernetes-client/c/blob/master/kubernetes/README.md#documentation-for-api-endpoints
> 
> I think https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/CoreV1API.md#CoreV1API_listNode is what you want.
-----------------------------------------------------------------------------------------------
Thank you very much for your answer and patience!

**Comment by wcamellia** [comment]
sorry , I do not find the "Ready" or "Notready" in  "https://github.com/kubernetes-client/c/blob/master/kubernetes/docs/CoreV1API.md#CoreV1API_listNode“ ， I only find the ”condition“ in ”v1_node_t“ structure ，I only want the ”Ready“  or ”Notready“ like using command ”kubectl get nodes “

**Comment by ityuhui** [comment]
I think "Ready" comes from the `type` of `condition`:
```
Status: True
Type: Ready
Message: kubelet is posting ready status
```

**Comment by wcamellia** [comment]
> I think "Ready" comes from the `type` of `condition`:
> 
> ```
> Status: True
> Type: Ready
> Message: kubelet is posting ready status
> ```
--------------------------------------------------------
Thank you very much !
