### ISSUE TITLE
Request to generate the C client library based on v1.25.2

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#146]
Hi @brendandburns 

Kubernetes v1.25.1 has been released.
Can I now regenerate the C client library based on the new version ? (via GitHub/Action https://github.com/kubernetes-client/c/actions/workflows/generate.yml)

**Comment by brendandburns** [comment]
Definitely. (and don't feel like you have to ask, since it sends a PR)

**Comment by ityuhui** [comment]
Due to a security issue introduced by Kubernetes v1.25.1, https://groups.google.com/a/kubernetes.io/g/dev/c/tA6LNOQTR4Q/m/zL73maPTAQAJ?utm_medium=email&utm_source=footer, I'm waiting for v1.25.2 to perform this task.

**Comment by ityuhui** [comment]
https://github.com/kubernetes-client/c/pull/151
