### ISSUE TITLE
Feature request, add lua support

### ISSUE THREAD

**Issue by dxlr8r** [kubernetes-client/c#147]
As described in: http://www.lua.org/pil/26.html

> for a C function to be called from Lua, we must register it, that is, we must give its address to Lua in an appropriate way.

It would require some work to add the boilerplate for all relevant functions, but once that is done it seems like the result would be that we can add lua to the list of client libraries.

**Comment by brendandburns** [comment]
Most of the code in this library is generated. I don't think it makes sense to add generic lua support to that C language generator.

I think there are two options:
* Scan the generated `.h` files and generate the correct Lua bindings from that (seems like it should be feasible)
* Use the independent Lua code generator (https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/lua.md) to generate the code directly from the Kubernetes swagger. There is a generic project for doing this at https://github.com/kubernetes-client/gen. You can look at the PR that added haskell for example (https://github.com/kubernetes-client/gen/commit/64d8840310dc0c9db13bebc596827795f3377ffb)

Let us know if there are questions or you decide to pursue either option.

**Comment by brendandburns** [comment]
fwiw, I also did a quick search and found this: https://luarocks.org/modules/f4z3r/luakube

I have no idea if it is any good...

Closing this issue since I don't think there's anything else to do here.
