### ISSUE TITLE
Unit test tool for c client

### ISSUE THREAD

**Issue by joyantamishu** [kubernetes-client/c#153]
Hi, 
Do you have any plan to come up with the k8s unit test facility in Kubernetes C client, or it's already been implemented? I see Golang client repo contains module like **fake** client, in order to unit test the k8s API, wondering if there is anything like that in C. 

Thanks in advance.

**Comment by brendandburns** [comment]
There's nothing like this currently planned, we would take PRs to achieve this, it would probably involve mocking out libcurl.
