### ISSUE TITLE
How to set up a non-root user,  to use the C API or k8s

### ISSUE THREAD

**Issue by wcamellia** [kubernetes-client/c#154]
How to set up a non-root user,  to use the C API or k8s？
my "C api" and "k8s" can not work under the non-root user

**Comment by ityuhui** [comment]
What's the error message your program outputs ?

Is your program running out of kube cluster or in cluster ?

And do you configure the right kubernetes config ?
- `~/.kube/config`in your home directory
- the environment variable `KUBECONFIG`
- function parameter `configFileName` of `load_kube_config`

**Comment by wcamellia** [comment]
my k8s cluster deploy in "root" user, but i change into "admin" user , 
when i  uese  the c api  in the non-root user，The error message my program outputs：
"kubeyaml_load_kubeconfig(): Cannot open the file /root/.kube/config.[Permission denied]
load_kube_config(): Cannot load the kubeconfig /root/.kube/config
Cannot load kubernetes configuration."

**Comment by wcamellia** [comment]
ok !thank you very much

**Comment by brendandburns** [comment]
Closing since the question is answered.
