### ISSUE TITLE
Cannot delete pod forcibly with CoreV1API_deleteNamespacedPod API

### ISSUE THREAD

**Issue by privmc** [kubernetes-client/c#158]
To delete a pod forcibly you need to set gracePeriodSeconds to zero. zero means delete immediately.

Example:

DELETE /api/v1/namespaces/{namespace}/pods/{name}?gracePeriodSeconds=0

However, if calling CoreV1API_deleteNamespacedPod with the gracePeriodSeconds parameter set to 0 the gracePeriodSeconds query parameter is not created in the HTTP request.

**Comment by ityuhui** [comment]
Yes. it's a problem.  Now, can you set a small value such as `gracePeriodSeconds=1` to walkaround this ?

Later, I want to fix this issue by introducing a magic number for the undefined parameter in openapi-generator.

e.g.
```c
#define INT_UNDEFINED -9997

...
    if (gracePeriodSeconds != INT_UNDEFINED)
    {
        keyQuery_gracePeriodSeconds = strdup("gracePeriodSeconds");
        valueQuery_gracePeriodSeconds = calloc(1,MAX_NUMBER_LENGTH);
        snprintf(valueQuery_gracePeriodSeconds, MAX_NUMBER_LENGTH, "%d", gracePeriodSeconds);
        keyPairQuery_gracePeriodSeconds = keyValuePair_create(keyQuery_gracePeriodSeconds, valueQuery_gracePeriodSeconds);
        list_addElement(localVarQueryParameters,keyPairQuery_gracePeriodSeconds);
    }
...

```

cc @brendandburns @wing328 @zhemant @michelealbano

**Comment by privmc** [comment]
Ok, thanks for the confirmation.

gracePeriodSeconds=1 does not work in my test.

If I do "kubectl delete pod <podname>" when the pod is in Running phase the kubectl commands hangs until the pod is forcibly deleted by sending a Pod delete with gracePeriodSeconds=0.

**Comment by ityuhui** [comment]
Got it.

If you need a fix now,  apply the patch below and build yourself please.

```diff
diff --git a/kubernetes/api/CoreV1API.c b/kubernetes/api/CoreV1API.c
index 0dff85d..cb0ce55 100644
--- a/kubernetes/api/CoreV1API.c
+++ b/kubernetes/api/CoreV1API.c
@@ -16088,7 +16088,6 @@ CoreV1API_deleteNamespacedPod(apiClient_t *apiClient, char * name , char * _name
     char *keyQuery_gracePeriodSeconds = NULL;
     char * valueQuery_gracePeriodSeconds = NULL;
     keyValuePair_t *keyPairQuery_gracePeriodSeconds = 0;
-    if (gracePeriodSeconds)
     {
         keyQuery_gracePeriodSeconds = strdup("gracePeriodSeconds");
         valueQuery_gracePeriodSeconds = calloc(1,MAX_NUMBER_LENGTH);
```
