### ISSUE TITLE
How can I use Node Proxy Api? 

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#159]
Hi, I m using kubernetes/c-client. 

I need to result of below command.

"curl -g --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET https://[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}/api/v1/nodes/${NODE_NAME}/proxy/summary"

But I can't find api in the CoreV1API, Related Node Api. 

How can I use this api?

**Comment by brendandburns** [comment]
I believe that this function will get you what you need:

https://github.com/kubernetes-client/c/blob/master/kubernetes/api/CoreV1API.h#L131

**Comment by minerba** [comment]
Hi @brendandburns  what API in that file ?? I can't find of "{node_name}/proxy/summary" url

**Comment by minerba** [comment]
Hi @brendandburns 
I found a API , But there is no Parser , related to uppon api . I need to develop the parser?

**Comment by brendandburns** [comment]
As far as I know there is no structure for the proxy API. What are you trying to do? It might help to have more context.

**Comment by minerba** [comment]
I need rootfs from node Api. because rootfs include data of Diskusage.

**Comment by brendandburns** [comment]
Note that you should be able to get the DiskPressure state from the node's conditions array, but that may not be sufficient for what you are looking for.
