### ISSUE TITLE
pod exec returns truncated output

### ISSUE THREAD

**Issue by nnarek** [kubernetes-client/c#168]
I am used examples/exec_pod/main.c to run the `seq 100000` command on a pod and I am getting wrong output.
To reproduce you should run that example and pipe output to `wc -l` to make sure that number of lines is less than 100000.You may need to run it few time to reproduce

I think issue come from libwebsockets, seems like there is no any guarantees that LWS_CALLBACK_CLIENT_RECEIVE callback will transfer data frame by frame

I am used 1.24 version of aws eks

**Comment by ityuhui** [comment]
Thank you for reporting this. I can reproduce it and need more time to investigate.
