### ISSUE TITLE
can not compile for centos 7

### ISSUE THREAD

**Issue by olegzhr** [kubernetes-client/c#175]
Can not compile sources for Centos 7 according to installation instructions  (for ubuntu it work)
 I got next error message:

/home/alertflex/c/kubernetes/src/list.c: In function ‘list_getElementAt’:
/home/alertflex/c/kubernetes/src/list.c:155:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(int i = 0; i < indexOfElement; i++) {
         ^
/home/alertflex/c/kubernetes/src/list.c:155:9: note: use option -std=c99 or -std=gnu99 to compile your code
/home/alertflex/c/kubernetes/src/list.c:163:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for(int i = 1; i < (list->count - indexOfElement); i++) {
         ^
make[2]: *** [CMakeFiles/kubernetes.dir/src/list.c.o] Error 1
make[1]: *** [CMakeFiles/kubernetes.dir/all] Error 2

**Comment by brendandburns** [comment]
This library is currently only tested on Debian based distributions, but that said, it looks like you should be able to add the arguments (`-std=c99 or -std=gnu99`) and make it work.

If you figure it out, we'd take a PR with the fix.
