### ISSUE TITLE
Invalid content type trying to get pod logs

### ISSUE THREAD

**Issue by ahmedyarub** [kubernetes-client/c#179]
I'm using CoreV1API_readNamespacedPodLog() to get the logs of a specific pod but k8s returns an error mentioning that text/plain is not supported. I rebuilt by removing [this line](https://github.com/kubernetes-client/c/blob/9dca01932d6aaa3416da1a0494a27100ccaadfd9/kubernetes/api/CoreV1API.c#L34123) and then it worked! I'm using Docker Desktop 4.17.1 which comes with Kubernetes 1.25.4. I checked the code of that version and it seems to me that that endpoint is supposed to produce plain/text response [since at least 2016](https://github.com/kubernetes/kubernetes/commit/e7a46a7c81105a831d4348769110c5644a946417)! Where is the problem exactly? In the client library? My Kubernetes installation?

**Comment by brendandburns** [comment]
That's odd. The content-type is coming from the OpenAPI schema that describes the Kubernetes API. It's possible that the OpenAPI schema is incompatible with the actual behavior of the Kubernetes API server, since it is manually curated.

What was the specific error message that you saw?

**Comment by ahmedyarub** [comment]
I have just rebuilt with the unpatched version and tested. Here is the response I had:

> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "only the following media types are accepted: application/json, application/yaml, application/vnd.kubernetes.protobuf",
>   "reason": "NotAcceptable",
>   "code": 406
> }

I can see the code which adds text/plain support but it doesn't seem to be working. That being said I can't imagine that this bug has been in Kubernetes for 7 years and nobody noticed!
