### ISSUE TITLE
BatchV1API_createNamespacedJob does not return the failing reason.

### ISSUE THREAD

**Issue by shayan-eftekhari** [kubernetes-client/c#189]
Hi,

I'm using the BatchV1API_createNamespacedJob API to create a Job.

If for any reason the process fails (e.g. if a job with the same name already exists), the API still returns a v1_job_t* with a kind equal to "Status" instead of "Job" but there is no way to understand the reason.

I digged into its implementation and I found this:

https://github.com/kubernetes-client/c/blob/6a82bde3470171aa3e8965f9e3766bda5fa5b170/kubernetes/api/BatchV1API.c#L327

The BatchV1APIlocalVarJSON local variable holds the actual reason, so I'm wondering if there is a way to report it back.

This might be also true on other APIs but I have not examined them yet.

Would you please let me know if there is a way to access the failure reason through the API, or if there is not, do you have a plan to make it possible? I'm wondering if it is possible to extend v1_job_status_t struct to hold such information.

Thank you in advance.

**Comment by ityuhui** [comment]
Does the `apiClient->response_code` meet your requirement ?

FYI https://github.com/kubernetes-client/c/issues/31#issuecomment-704710140

**Comment by ityuhui** [comment]
What's the value of `elementToReturn` in your code ?

https://github.com/kubernetes-client/c/blob/6a82bde3470171aa3e8965f9e3766bda5fa5b170/kubernetes/api/BatchV1API.c#L328

**Comment by shayan-eftekhari** [comment]
elementToReturn = {
    api_version = "v1",
    kind = "Status",
    metadata = {
        // All fields are 0 or NULL
    },
    spec = NULL,
    status = {
        // All fields are 0 or NULL
    }
}

**Comment by ityuhui** [comment]
Can you try to debug the function `v1_job_parseFromJSON` and `v1_job_status_parseFromJSON` to check why the `v1_job_status_t` is NULL ?

```bash
# Build
mkdir build
cd build
# If you want to use `gdb` to debug the C client library, add `-DCMAKE_BUILD_TYPE=Debug` to the cmake command line, e.g.
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local ..
make
```

**Comment by shayan-eftekhari** [comment]
Here is the content of BatchV1APIlocalVarJSON that is passed to the v1_job_parseFromJSON function:

`{
    "apiVersion": "v1",
    "kind": "status",
    "metadata": null,
    "status": "Failure",
    "message": "jobs.batch \"hello-world\" already exists",
    "reason": "AlreadyExists",
    "code": 409,
    "details": {
        "name": "foo",
        "kind": "jobs",
        "group": "batch"
    }
}`

Then, the v1_job_parseFromJSON funtion extracts the status part:

cJSON *status = cJSON_GetObjectItemCaseSensitive(v1_jobJSON, "status");

which is a JSON string, "Failure", without any child (type: 16) and the passes it to the v1_job_status_parseFromJSON function. This function is then repeatedly calls cJSON_GetObjectItemCaseSensitive function to extract fields including "active", "completedIndexes", "completionTime", etc. However, cJSON_GetObjectItemCaseSensitive expects its input to be JSON object with a child and since it doesn't find a child, it returns NULL for all of them.

**Comment by ityuhui** [comment]
I see.
So if you want detailed error messages instead of error codes like `409`, I think the only way is to use generic client https://github.com/kubernetes-client/c/issues/31#issuecomment-707207108 to send the request and parse the json by yourself.
