### ISSUE TITLE
No way to get data out of a watch callback

### ISSUE THREAD

**Issue by rcorre** [kubernetes-client/c#194]
`data_callback_func` takes a `void**` for the incoming data, and a `long *` for the data length. This is fine if you just want to print the object like the examples do, but what if you want to store the data in some structure, or pass it to another component?

It would be useful to have a "user pointer" so we could pass in our own store/component to handle the data, similar to how the [writeDataCallback](https://github.com/kubernetes-client/c/blob/master/kubernetes/src/apiClient.c#L7) passed to curl has a `userp` field.

**Comment by ityuhui** [comment]
A good suggestion!  But I have some questions about your use case:

As you know, `data_callback_func` is a function that requires user to provide/implement, it will only be called in the libcurl callback `writeDataCallback` https://github.com/kubernetes-client/c/blob/c223563bda143b3ca9e38cbee5782b37cad040a3/kubernetes/src/apiClient.c#L471

How the new `userp-for-data_callback_func` is passed into `writeDataCallback` ?

And I think in the customized `data_callback_func`, you can call a handler function, e.g.
https://github.com/kubernetes-client/c/blob/c223563bda143b3ca9e38cbee5782b37cad040a3/examples/watch_list_pod/main.c#LL68C3-L68C3

**Comment by rcorre** [comment]
> How the new userp-for-data_callback_func is passed into writeDataCallback ?

As the `data_callback_func` is a field on the `apiClient`, the user pointer could be another field there, so you'd have something like:

```
apiClient->data_callback_func(apiClient->callbackData, &apiClient->dataReceived, &apiClient->dataReceivedLen); 
```

> And I think in the customized data_callback_func, you can call a handler function

There's still no way to get data out of the handler you pass in. In the example `on_pod_event_comes` just prints the value, but if you wanted to put it in some data structure, or a database, there's no way to do that without using a global.

**Comment by ityuhui** [comment]
I understand. This is a nice addition to `data_callback_func`.
Would you like to create a PR to implement your idea ? 
And I have a suggestion for the usage (put the callbackData in the last place):
```c
apiClient->data_callback_func(&apiClient->dataReceived, &apiClient->dataReceivedLen, apiClient->callbackUserData);
```

**Comment by ityuhui** [comment]
This code change needs to be committed the upstream
https://github.com/OpenAPITools/openapi-generator/blob/afca85acf577c4117e6eda650d2e228726b57f5c/modules/openapi-generator/src/main/resources/C-libcurl/apiClient.h.mustache#L27
first.
