### ISSUE TITLE
Make websocket dependency optional

### ISSUE THREAD

**Issue by rcorre** [kubernetes-client/c#195]
It seems that the libwebsockets dependency is only necessary for a [small subset of features](https://github.com/kubernetes-client/c/issues/56). Would it be possible to make this dependency optional in CMake, and conditionally include the websocket-related features? It would be nice if consumers who don't need exec/attach/portforward could omit websockets from their build.

**Comment by brendandburns** [comment]
We'd be happy to take a PR to make this change.

Thanks
