### ISSUE TITLE
issue in postData to support 32bit

### ISSUE THREAD

**Issue by hai22yu23** [kubernetes-client/c#199]
postData in apiClient.c  has issues for supporting 32bit:

/* it should add type cast (curl_off_t)

curl_easy_setopt(handle, CURLOPT_POSTFIELDSIZE_LARGE,
                            (curl_off_t) strlen (bodyParameters));

-     * libcurl API curl_easy_setopt requires the third parameter
-     * has to be passed with correct type depending on specific option.
-     * For CURLOPT_POSTFIELDSIZE_LARGE option,
-     * it has to be type curl_off_t which is expected to be
-     * 64bit whether on 32bit or 64bit platform.

**Comment by brendandburns** [comment]
This needs to be fixed in the upstream OpenAPI generator:

**Comment by ityuhui** [comment]
The the upstream PR https://github.com/OpenAPITools/openapi-generator/pull/16238 is merged. I'd like to regenerate the client now.
