### ISSUE TITLE
How can I detect that API server is disconnected while using watch function?

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#202]
Hello

I'd like to distinguish between no events from the API server during the watch behavior and a disconnected libcurl.
If the API server is disconnected, I have to re-run the watch function.

In the current code, the only way to perform a periodic watch with a timeout, which means that I'll not receive notification from the API server for a worst-case timeout.
I was hoping you could help me figure out what to do fix this.

Thanks in advance.

**Comment by brendandburns** [comment]
That's the only way to do it, since no data is sent if there are no events, the only other way to detect it is via a TCP timeout, but that's not currently supported.

We could consider adding support for that via:
https://curl.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

cc @ityuhui

**Comment by clearday4** [comment]
my questions are as follows.
If I call the API with watch option, curl_easy_perform should have already returned, so how do I know that the TCP connection has been lost?
If I could know by the result of curl_easy_perform(), it doesn't make sense for the watch behavior.
I think I need to check via callback function. Is it possible to check if TCP is disconnected using CURLOPT_XFERINFOFUNCTION?

**Comment by ityuhui** [comment]
We already support `CURLOPT_XFERINFOFUNCTION` via `progress_func`

https://github.com/kubernetes-client/c/blob/0f0f4cc228415b80889f640b7ac2967dc09bbec5/kubernetes/include/apiClient.h#L28

You can have a try.
