### ISSUE TITLE
Remove printf from internal function

### ISSUE THREAD

**Issue by homer6** [kubernetes-client/c#225]
The generic client is working well, however there's a quick tweak that I think would be useful.

Using the generic client, I'm seeing printf to stdout in the 200-level case and the 400-level case.

Would prefer if it didn't write to stdout. The response code is retrievable from the api_client, so I can handle it in the application.

https://github.com/kubernetes-client/c/blob/d0763b643f5da72604dc3097f69c2a67245d84c5/kubernetes/src/generic.c#L59

**Comment by brendandburns** [comment]
Yeah, I think it is fine to send a PR to remove those printfs.
