### ISSUE TITLE
Conan support

### ISSUE THREAD

**Issue by ydcpp** [kubernetes-client/c#229]
Hi, is there any plan on adding the project to Conan in the future?

**Comment by ityuhui** [comment]
We welcome the contributions of adding this to Conan.

Just like @ahmedyarub did with vcpkg https://github.com/kubernetes-client/c/blob/master/docs/vcpkg.md.

**Comment by ydcpp** [comment]
okay thanks, I will create PR associated with this issue when it's ready.
