### ISSUE TITLE
About metric API

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#23]
Do you have a plan to support "apis/metrics.k8s.io/v1beta1" APIs for gathering resources?

**Comment by ityuhui** [comment]
Hi @clearday4 

I think the metrics API support depends on CRD (CustomResourceDefinition) support.  So we will not start to support it before CRD is [supported](https://github.com/kubernetes-client/c/issues/8).

Thank you for your proposal for the feature. I will append here if there is any further progress.

**Comment by brendandburns** [comment]
The other option is to implement the generic API similar to what the Java code does here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java

I'll see if I have cycles to add that.

**Comment by brendandburns** [comment]
I've started working on the generic client.

**Comment by brendandburns** [comment]
The generic client has now merged.

There is an example here:

https://github.com/kubernetes-client/c/blob/master/examples/generic/main.c

You can use
apiGroup: "metrics.k8s.io"
version: "v1beta1",
resourcePlural: "nodes" or "pods"

and the generic client to access metrics.

**Comment by clearday4** [comment]
Thank you for kind answer
It will be very helpful for us.

**Comment by clearday4** [comment]
closed
