### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by joyanta55** [kubernetes-client/c#251]
Hi,
Is there any plan to add `BUILD` files to support `Bazel` in the future?
Best

**Comment by brendandburns** [comment]
BUILD files for what? If it is for specific clients (e.g. Python) that would be something that you should raise in the specific repo (e.g. https://github.com/kubernetes-client/java)

**Comment by joyanta55** [comment]
> ~BUILD files for what? If it is for specific clients (e.g. Python) that would be something that you should raise in the specific repo (e.g. https://github.com/kubernetes-client/java)~
> 
> Oops, I was in the wrong repo, I thought this was the kubernetes-client/gen repo :(
> 
> No current plans but happy to review a PR.

created a PR with this feature.

**Comment by brendandburns** [comment]
Closing since #254 merged.
