### ISSUE TITLE
[WIP][Feature]Configuraion support for kubernetes-client/c

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#4]
Hi @brendandburns 

In order to meet the requirement of client [bronze](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) requirements , I begin to implement the configuration utility now.

My design is adding a directory "config" under the directory kubernetes

```
c/kubernetes/config 
```
and some source files
```
c/kubernetes/config/kube_config.h
c/kubernetes/config/kube_config.c
```

to hold the utility functions.

What methods should we support at least ?
* Basic Auth (username/password)
* X509 Client certificate 
* Bearer tokens
* encryption/TLS

**Comment by brendandburns** [comment]
We should definitely also support `exec` 
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration

and probably clouds (GCP, Azure, AWS) auth.

Ideally we can make it pluggable so that people can dynamically register new authentication methods.

**Comment by ityuhui** [comment]
Hi @brendandburns 

Do you mean we support ```exec``` and make GCP, Azure, AWS client auth as executable, 
```shell
kubernetes/config/client_auth_plugins/gcp_client_auth
kubernetes/config/client_auth_plugins/azure_client_auth
kubernetes/config/client_auth_plugins/aws_client_auth
```
pass the client auth executable location and parameters to kube_exec_config

e.g.
In kubernetes/config/kube_config.c

```c
int kube_exec_config(const char *exec_command, void *arg_list_for_exec)
{
    ExecCredential *ec = execute_and_return_result(exec_command, arg_list_for_exec);
    
    if(ec->status->token != NULL){
        get_client_token_from_exec_credential(ec);
    } else if(ec->status->clientCertificateData!= NULL){
        get_client_certifiacate_from_exec_credential(ec);
    }


    ...
}
```

In user's source 
```c
int main()
{
    ...
    struct arg_list{
        char *username;
        char *pwd;
        char **envs;
        echar **args;
    } arg ;

    arg->username = strdup(argv[1]);
    arg->password = strdup(argv[2]);

    kube_exec_config("kubernetes/config/plugins/k8s_auth_plugins/aws_client_auth", &arg);
    ...
}

```

And I also have another idea that implements the plugin as a library

```shell
kubernetes/config/client_auth_plugins/libgcp_client_auth.so
kubernetes/config/client_auth_plugins/libazure_client_auth.so
kubernetes/config/client_auth_plugins/libaws_client_auth.so
```
In plugin
```c
typedef struct  {
    void (*execute_and_return_result)(void *);
    int (*get_client_auth_from_exec_credential)(void *ExecCredential *);
} client_auth_plugin ;
```

In kubernetes/config/kube_config.c
```c
int kube_exec_config(struct client_auth_plugin *aws, void *arg_list_for_exec)
{
    ExecCredential *ec = aws->execute_and_return_result( arg_list_for_exec);

    aws->get_client_auth_from_exec_credential(ec);
    ...
}
```

```c
int main()
{
    ...
    struct arg_list{
        char *username;
        char *pwd;
        char **envs;
        echar **args;
    } arg ;

    arg->username = strdup(argv[1]);
    arg->password = strdup(argv[2]);

    struct client_auth_plugin *gcp;
    void *h = dlopen("kubernetes/config/plugins/libgcp_client_auth.so", RTLD_NOW|RTLD_GLOBAL);

    gcp->execute_and_return_result = dlsym(h, "execute_and_return_result" );
    gcp->get_client_auth_from_exec_credential= dlsym(h, "get_client_auth_from_exec_credential" );

    kube_exec_config(gcp, &arg);
    ...
}
```

Which solution do you prefer ?

**Comment by ityuhui** [comment]
I plan

1. Support GCP, Azure, AWS by {so|dll} plugin library

2. Support ```exec``` following https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration

3. Customers use plugin library to add/register their auth method. such as LDAP, etc ...

**Comment by ityuhui** [comment]
Because [openapi-generator](https://github.com/OpenAPITools/openapi-generator)/[c](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/C-libcurl) does not support SSL client authentication now. I will go to work on supporting SSL client authentication in openapi-c-generator project first.

**Comment by ityuhui** [comment]
The PR https://github.com/OpenAPITools/openapi-generator/pull/5719 implements SSL client authentication.

**Comment by ityuhui** [comment]
SSL client authentication is implemented by https://github.com/kubernetes-client/c/pull/7

**Comment by ityuhui** [comment]
X509 client certificate in kube config file is supported by the PR https://github.com/kubernetes-client/c/pull/9

**Comment by ityuhui** [comment]
Configuration of service token and CA in cluster is supported by the PR https://github.com/kubernetes-client/c/pull/10

**Comment by ityuhui** [comment]
exec (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration) is supported by the PR #12

**Comment by ityuhui** [comment]
auth provider plugin framework and OIDC plugin are implemented by the PR https://github.com/kubernetes-client/c/pull/26

**Comment by ityuhui** [comment]
Considering most of configuration cases are supported, I will suspend this task from now.

If other authentication method (e.g. AWS, Azure, GCP) is needed,  I can continue by demand. And PR is welcome.

**Comment by ityuhui** [comment]
/remove-lifecycle stale

Use this ticket to trace the current status of configuration support.
