### ISSUE TITLE
How can I Use 'AutoscalingV1API_patchNamespacedHorizontalPodAutoscalerStatus' ?

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#49]
Hi. I m trying to make hpa Update api. 

I have confirmed that Below CURL message is working fine.

curl -k  -g \
    -X PATCH \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/strategic-merge-patch+json'  \
    https://[${MY_SERVICE_HOST}]:${MY_SERVICE_PORT}/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/acpf110-cip0?<<'EOF'
{ }
EOF

But  'AutoscalingV1API_patchNamespacedHorizontalPodAutoscalerStatus' call apiClient_invoke.
apiClient_Invoke makes Header like 'Content-Type: application/json' + ... etc   But this Content-Type return Bad Request Error. 

PATCH Request need to diffrent Apiclient_invoke  function. 

Not only this problem but also object_t parameter is not used anywhere. 

in AutoscalingV1API_patchNamespacedHorizontalPodAutoscalerStatus  "object_t* object parameter" is not used anywhere. 

so Can't input changed part. 

If the above words are wrong, please let me know the correct usage of

 'AutoscalingV1API_patchNamespacedHorizontalPodAutoscalerStatus'

I don't know what is object_t?... and then how can I makes curl message (Like above curl Message) by using apiClient_invoke...

thank you.

**Comment by ityuhui** [comment]
Hi @minerba

For now, ``object_t`` is not supported by ``apiClient_invoke``.

You can use  [generic client](https://github.com/kubernetes-client/c/blob/master/examples/generic/main.c) to operate the resources (e.g. horizontalpodautoscalers) directly now.

**Comment by minerba** [comment]
Thank U @ityuhui 
I understood your answer. 

But I Can't understand to "AutoscalingV1API_patchNamespacedHorizontalPodAutoscalerStatus" function  makes inapposite Content-type. 

e.g)  Content-type: application/json  returns 400 Error.    But Content-type: application/strategic-merge-patch+json return 200 Success. 

Let me know if you know solution about this problem.

**Comment by minerba** [comment]
Thank U
