### ISSUE TITLE
How can I solve this Error...?

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#50]
Hi, @ityuhui 
As you said I tried to update hpa using generic client.

But generic Make Path function  does not include Header par. 

How about add Header Parameters in generic Make Path function?

**Comment by ityuhui** [comment]
The generic client does not have a build-in function to add the header parameters.

For now, you need add them by yourself, please refer to the code in apiClient.c
```c
void apiClient_invoke(...,
                                    list_t        *headerParameters,
                                    ...)
...
        curl_slist_append(headers, headerValueToWrite);
...
        curl_easy_setopt(handle, CURLOPT_HTTPHEADER, headers);
...
```

Thank you for reporting this problem, I will implement this function to add header parameter to generic function sometimes later.  

And welcome you to implement this feature too !
