### ISSUE TITLE
PATCH function needs to be added

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#51]
When using only the PUT function, all Json properties must be written.

genericClient has PUT/GET/POST function but there is no function to PATCH in the genericClient function.

**Comment by ityuhui** [comment]
Hi @minerba 

Are these functions what your want ?

```c
char* Generic_patchNamespacedResource(genericClient_t *client, const char *ns, const char *name, const char* body) {
    char path[128];
    makeNamespacedResourcePath(path, client, ns, name);
    return callInternal(client, path, "PATCH", body);
}

char* Generic_patchResource(genericClient_t *client, const char *name, const char* body) {
    char path[128];
    makeResourcePath(path, client, name);
    return callInternal(client, path, "PATCH", body);
}
```

**Comment by minerba** [comment]
yes, I want.....

**Comment by ityuhui** [comment]
I will deliver it soon.

**Comment by ityuhui** [comment]
These functions are committed by https://github.com/kubernetes-client/c/pull/52

Please refer to the [example](https://github.com/kubernetes-client/c/blob/master/examples/generic/main.c) to get the usage. e.g. ``Generic_patchResource``
