### ISSUE TITLE
So far, the C client does not support websocket releated features e.g. exec, attach, and port-forward.

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#56]
So far, the C client does not support websocket releated features e.g. exec, attach, and port-forward.

_Originally posted by @ityuhui in https://github.com/kubernetes-client/c/issues/55#issuecomment-808639654_

@ityuhui
Do you have any plans to provide exec Pod api in the future?

(CoreV1API_connectGetNamespacedPodPortforward(apiClient_t *apiClient, char * name , char * _namespace , int ports ))

**Comment by ityuhui** [comment]
I'm interested but not sure when to implement.
First of all I need find a websocket library because libcurl does not support websocket now...
