### ISSUE TITLE
Need to modify parameters

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#61]
I think functions should receive "const char*" rather than "char*". 

for example name or _namespace are unlikely to be modified.

**Comment by ityuhui** [comment]
Could you please give a function for example ?

**Comment by minerba** [comment]
I have a Compile warning in this function 

Because of not const .

v1_pod_t* CoreV1API_readNamespacedPod(apiClient_t *apiClient, char * name , char * _namespace , char * pretty , int exact , int _export )

parameters name, _namespace, pretty are unlikely to be modified. 

I suggest that functions that take a parameter "char *" are changed to "const char*"

The same for other functions in Directory '/kubernetes/api/*'.

**Comment by ityuhui** [comment]
Good suggestion! I want to do this before but mark it as low priority. 
And welcome PR, the change should be done in the [openapi-generator](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/C-libcurl) project.

**Comment by minerba** [comment]
Ok. Thank U I will PR to openapi-generator project.

**Comment by ityuhui** [comment]
Hi @minerba 

Do you have interest to fix this issue ?

The steps:
1.  Update the files in the directory: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/C-libcurl
2.  Execute the script in https://github.com/kubernetes-client/gen with the configuration https://github.com/kubernetes-client/c/blob/master/settings to get a generated directory `kubernetes`
(The step 2 can be replaced with below commands if you want to use the current swagger spec of Kubernetes API server:
    2. Execute the command in the directory of repo `OpenAPITools/openapi-generator`
```shell
mvn clean package
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ../c/kubernetes/swagger.json   -g c    -o ../kubernetes --skip-validate-spec
```
to get get a generated directory `kubernetes`)

3.  Copy the files in `kubernetes` to overwrite the directory of this repo `c/kubernetes/` except `CMakeLists.txt`
4. Follow the https://github.com/kubernetes-client/c/blob/master/README.md to build and test 
5. Create a PR to apply to merge.

**Comment by ityuhui** [comment]
@minerba

You need submit 2 PR.

- The 1st PR is in OpenAPI-Generator, take this PR https://github.com/OpenAPITools/openapi-generator/pull/10034 as example
- The 2nd PR will be here. FYI https://github.com/kubernetes-client/c/pull/68

**Comment by ityuhui** [comment]
Hi @minerba 

Are you still working on this ticket ?

**Comment by minerba** [comment]
@ityuhui 
sorry Well... How can I apply this command? "/remove-lifecycle rotten"

**Comment by ityuhui** [comment]
> How can I apply this command? "/remove-lifecycle rotten"

I have done it.

**Comment by minerba** [comment]
@ityuhui Thank you:)

**Comment by ityuhui** [comment]
I will fix it.  Reopen this ticket to trace.

**Comment by minerba** [comment]
Thanks your Pr.
