### ISSUE TITLE
The type of target_port of v1_service_port_t is invalid.

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#63]
The type of target_port in the v1_service_port_t structure is abnormal.
```c
typedef struct v1_service_port_t {
    char *name; // string
    int node_port; //numeric
    int port; //numeric
    char *protocol; // string
    object_t *target_port; //object  <--- it is not an object type

} v1_service_port_t;
```

I think target_port should be an integer type like port and node_port.
In the v1_service_port.c, target port is parsed from object_parseFromJSON() so it returns null.
object_parseFromJSON() is always return NULL.
when I changed target_port to integer type and got it with cJSON_GetObjectItemCaseSensitive()  as sams as port, it works properly.

please consider about it.
Thanks

**Comment by brendandburns** [comment]
targetPort is an IntOrString type in the swagger (https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json)

We may very well not handle these correctly right now.

**Comment by brendandburns** [comment]
See:
https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
For example.

There are a number of custom types we will need to add:
https://github.com/kubernetes-client/java/tree/master/kubernetes/src/main/java/io/kubernetes/client/custom

**Comment by clearday4** [comment]
> See:
> https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
> For example.
> 
> There are a number of custom types we will need to add:
> https://github.com/kubernetes-client/java/tree/master/kubernetes/src/main/java/io/kubernetes/client/custom

Thank you @brendandburns 
would you add the new custom type "IntOrString" ?

**Comment by brendandburns** [comment]
Yes, I think that would be fine. We'll need to add custom serialize/deserialize code to handle that.

**Comment by ityuhui** [comment]
I'm working on this ticket now. First of all, I will add the support for `IntOrString`

**Comment by ityuhui** [comment]
I will deliver 3 pull requests to address the support for `IntOrString `
- https://github.com/OpenAPITools/openapi-generator/pull/11074
- TODO in kubernetes-client/gen
- TODO in kubernetes-client/c

**Comment by ityuhui** [comment]
The type `IntOrString` is supported now.

Alough there are some custom types need support,  no issue is reported so far.
Can we close this ticket now ? @brendandburns
