### ISSUE TITLE
what is the version of library?

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#64]
According to the README.md in kubernetes directory
The version is mentioned that
API version: v1.17.4
Package version:
Build package: org.openapitools.codegen.languages.CLibcurlClientCodegen

Is it the right API Version?
And there is no ABI version for library?

**Comment by ityuhui** [comment]
The code is generated according to the kubernetes API swagger v1.17.4

**Comment by brendandburns** [comment]
We should regenerate the library for a later version of Kubernetes.

**Comment by ityuhui** [comment]
> We should regenerate the library for a later version of Kubernetes.

Which version is better for now ? I see the latest official release is v1.21.1

**Comment by brendandburns** [comment]
Ultimately, we should generate a new version for every version of Kubernetes, see for example the Java client:

https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility

But for now, let's jump forward to 1.21.1

But we should tag the repo with a '0.1' first so that people can check out the code for usage with older Kubernetes.

**Comment by ityuhui** [comment]
OK. I will do it.

**Comment by ityuhui** [comment]
I'm working on the websocket/exec support for c client now (maybe delivered in 1 week). It's better to tag after this feature is merged, then users can exec command in pod with the older Kubernetes.

**Comment by brendandburns** [comment]
ok, works for me.

We should also think about how we could release .deb/.rpm packages

**Comment by ityuhui** [comment]
> We should also think about how we could release .deb/.rpm packages

Agree. then we can integrate them into package managers e.g. apt/yum.

**Comment by clearday4** [comment]
Thanks @brendandburns @ityuhui 
BTW, libkubernestes.so doesn't have an API version?

**Comment by clearday4** [comment]
> I'm working on the websocket/exec support for c client now (maybe delivered in 1 week). It's better to tag after this feature is merged, then users can exec command in pod with the older Kubernetes.

That's a great news!!
What websocket library did you select?

**Comment by brendandburns** [comment]
@clearday4 Kubernetes maintains a n-2 compatability, so a 1.20 library should work with 1.18. It will _mostly_ work with older versions too, but it is less guaranteed.

We will plan to align the versioning of this library with the Kubernetes version, so hopefully going forward you will be able to select a version that works for your version of kubernetes.

**Comment by ityuhui** [comment]
> What websocket library did you select?

It's libwebsockets

**Comment by ityuhui** [comment]
I will start to work for this task. 
Firstly, tag current version using below command after https://github.com/kubernetes-client/c/pull/80 is merged: 

```shell
git tag -a v0.1.0 -m "version 0.1.0"
```

**Comment by ityuhui** [comment]
I have tagged the current code as "v0.1.0"
https://github.com/kubernetes-client/c/tags

And created a pre-release:
https://github.com/kubernetes-client/c/releases/tag/v0.1.0

Next, I will upgrade the swagger version to Kubernetes v1.22.1

**Comment by ityuhui** [comment]
This problem is resoved.
