### ISSUE TITLE
Instructions to running openapi generator

### ISSUE THREAD

**Issue by jiria** [kubernetes-client/c#8]
Hello,

Can you please provide instructions/script on rerunning the openapi generator? Specifically, trying to target some CRDs with the C client.

**Comment by ityuhui** [comment]
Hi @jiria 

There are 2 methods to re-run the openapi generator.

1.  The official method:  
use the script in https://github.com/kubernetes-client/gen
with the configuration https://github.com/kubernetes-client/c/blob/master/settings

2. After you get the kubernets API specification "swagger.json" by the method #1 
you can re-run openapi-generator by this command in openapi-generator directory.

```shell
mvn clean package
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ${kubernetes-client-c-dir}/kubernetes/swagger.json   -g c    -o ../kubernetes-client-c --skip-validate-spec
```

You can try it for your case.  I have not test for CRD. 
Welcome to PR to support CRD!

**Comment by ityuhui** [comment]
Hi @brendandburns

Do we support add user's CRD openapi/swagger spec to the swagger.json? by manual or by kubernetes-client/gen ?

Or users only can create/query/update/delete CustomResourceDefinition in kuberntes-client/c 
but they need handle their own CRD model/api by their application ?

**Comment by ityuhui** [comment]
Hi @jiria

These 2 files maybe useful for you to try.

https://github.com/kubernetes-client/c/blob/master/kubernetes/api/CustomObjectsAPI.h
https://github.com/kubernetes-client/c/blob/master/kubernetes/api/CustomObjectsAPI.c

**Comment by brendandburns** [comment]
There are example instructions here:
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md

For the Java client, we could do something similar for C

**Comment by ityuhui** [comment]
/remove-lifecycle stale

This defect traces the client for CRD.

**Comment by jiria** [comment]
Thank you for the pointers. I had to switch to the C# SDK due to existing dependencies, so did not really get too far here. But I hope other folks will find this useful as well. Not closing in case you want to track this further.

**Comment by ityuhui** [comment]
Thank you @jiria for proposing this requirement. I start to work on this feature from now.

**Comment by ityuhui** [comment]
The best method to support CRD is [generic client](https://github.com/kubernetes-client/c/blob/master/examples/generic/main.c) now.
