### ISSUE TITLE
Create the .deb/.rpm package for the C client library

### ISSUE THREAD

**Issue by ityuhui** [kubernetes-client/c#81]
Let's create the .deb package firstly.

**Comment by brendandburns** [comment]
Sound good to me, what distros should we target? I suggest Ubuntu 18/20 and Debian 9/10

**Comment by brendandburns** [comment]
We should also formalize the semantic versioning and things like release tags in the git repo.

Perhaps the right thing to do is to write a markdown doc describing the process first, and then implement it?

**Comment by ityuhui** [comment]
> Sound good to me, what distros should we target? I suggest Ubuntu 18/20 and Debian 9/10

I agree. Let's support below 4 distros (x86_64 only)
- Ubuntu 18.04 LTS
- Ubuntu 20.04 LTS
- Debian 9
- Debian 10

**Comment by ityuhui** [comment]
> We should also formalize the semantic versioning and things like release tags in the git repo.
> 
> Perhaps the right thing to do is to write a markdown doc describing the process first, and then implement it?

Sure. Would you like draft the doc  ? 
Or give me a reference doc that other project is using and let me draft.

**Comment by brendandburns** [comment]
Here's an example from the Java project:

https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility

Thanks!

**Comment by ityuhui** [comment]
Got it. I will do it.

**Comment by ahmedyarub** [comment]
are you going to use CPack?

**Comment by ityuhui** [comment]
I haven't started building the package.

Do you think CPack is better than official [debmake](https://www.debian.org/doc/manuals/debmake-doc/) for the C client library ?

**Comment by ahmedyarub** [comment]
> I haven't started building the package.
> 
> Do you think CPack is better than official [debmake](https://www.debian.org/doc/manuals/debmake-doc/) for the C client library ?

Because CPack can generate deb files in addition to many other formats https://cmake.org/cmake/help/latest/manual/cpack-generators.7.html

**Comment by ityuhui** [comment]
@ahmedyarub  Great ! I will take a look at this solution.

**Comment by ityuhui** [comment]
https://github.com/kubernetes-client/c/pull/94 will deliver the feature of deb package.

**Comment by ityuhui** [comment]
The deb package can now be created.
The rpm package will be supported if needed.
