### ISSUE TITLE
vcpkg integration

### ISSUE THREAD

**Issue by ahmedyarub** [kubernetes-client/c#83]
I'm adding vcpkg integration for this library https://github.com/microsoft/vcpkg/pull/20255
I tested it on Windows and it worked without any problem.
@ityuhui I remember that in a previous comment you said that the installation script would not work without adding the DESTINATION parameter. I had to patch that in vcpkg for the port to work. Can you please make sure that the installation really doesn't work without that parameter?

**Comment by ityuhui** [comment]
I tested it in Ubuntu 18.04 LTS, yes, `DESTINATION` is needed by this platform.

**Comment by ahmedyarub** [comment]
Merged

**Comment by ityuhui** [comment]
@ahmedyarub
Could you please update the readme https://github.com/kubernetes-client/c/blob/master/README.md to tell user how to use it in vcpkg ?

**Comment by ahmedyarub** [comment]
> @ahmedyarub
> Could you please update the readme https://github.com/kubernetes-client/c/blob/master/README.md to tell user how to use it in vcpkg ?

https://github.com/kubernetes-client/c/pull/85
