### ISSUE TITLE
Memory Leak in CoreV1API

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#96]
Hi 

I found some defect that Memory Leak in CoreV1API.c

In the "CoreV1API_deleteNamespacedPod" function, the localVarToReplace variable calls malloc, but if the __namespace variable is NULL, it moves to end and the function ends without calling free.
Other functions are also confirmed to have memory leak.

It needs to be fixed as soon as possible.

**Comment by ityuhui** [comment]
Could you please provide a sample ? 

The example [delete_pod](https://github.com/kubernetes-client/c/blob/master/examples/delete_pod/main.c) has passed valgrind test. No memory leak is reported.

**Comment by minerba** [comment]
Hi @ityuhui 

In normal cases, memory leak does not occur, but if (__namespace == NULL)
Memory leak occurs.

**char* localVarToReplace_name = malloc(sizeOfPathParams_name);**
    sprintf(localVarToReplace_name, "{%s}", "name");

    localVarPath = strReplace(localVarPath, localVarToReplace_name, name);

    // Path Params
    long sizeOfPathParams_namespace = strlen(name)+3 + strlen(_namespace)+3 + strlen("{ namespace }");
    if(_namespace == NULL) {
        goto end;
    }
============= end ==============
end:
    free(localVarPath);
    return NULL;

**Comment by minerba** [comment]
@ityuhui  thanks for your reply. I hope it will be fixed soon
