### ISSUE TITLE
NULL check order 

### ISSUE THREAD

**Issue by minerba** [kubernetes-client/c#97]
I think Below code have some    

```
 // Path Params
    long sizeOfPathParams_name = strlen(name)+3 + strlen(_namespace)+3 + strlen("{ name }");
    if(name == NULL) {
        goto end;
    }``
```

I think strlen(name) has to do after name NULL Check 

```
 // Path Params
    if(name == NULL) {
        goto end;
    }``
    long sizeOfPathParams_name = strlen(name)+3 + strlen(_namespace)+3 + strlen("{ name }");
```

**Comment by ityuhui** [comment]
The code is generated by [openapi-generator/c-libcurl](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/C-libcurl/api-body.mustache), its purpose is to share the code 
```c
long sizeOfPathParams_{{{paramName}}} = {{#pathParams}}{{#isLong}}sizeof({{paramName}})+3{{/isLong}}{{#isString}}strlen({{paramName}})+3{{/isString}}{{^-last}} + {{/-last}}{{/pathParams}} + strlen("{ {{baseName}} }");
```
with all data types.

Considering there is no danger to do so, I will not change it right now.

Thank you for reporting this issue!

**Comment by minerba** [comment]
@ityuhui 
Ok, Thank you.
